USE [JoyotaSA]
--HACIA DEPARTAMENTO
GO 
ALTER TABLE Administrativo ADD CONSTRAINT FK_ADMINISTRATIVO_DEPARTAMENTO
FOREIGN KEY(IDDEPARTAMENTO)
REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
--HACIA EMPLEADO
GO 
ALTER TABLE Administrativo ADD CONSTRAINT FK_ADMINISTRATIVO_EMPLEADO 
FOREIGN KEY (IDEMPLEADO)
REFERENCES Empleado(IDEMPLEADO)

GO
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_EMPLEADO
FOREIGN KEY (IDEMPLEADO)
REFERENCES EMPLEADO(IDEMPLEADO)
--HACIA VENTAS
GO
ALTER TABLE Ventas ADD CONSTRAINT FK_VENDEDOR_SUCURSAL
FOREIGN KEY (IDSucursal)
REFERENCES Sucursal(IDSucursal)--pueda que este mal y sea de ventas a sucursal
------REFERENCIAS DE LA BODEGA
GO
ALTER TABLE SUCURSAL ADD CONSTRAINT FK_SUCURSAL_BODEGA
FOREIGN KEY(IDBODEGA)
REFERENCES BODEGA(IDBODEGA)
--HACIA SUCURSAL
--GO
--ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_SUCURSAL
--FOREIGN KEY(IDSUCURSAL)
--REFERENCES SUCURSAL(IDSUCURSAL)
GO
ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_SUCURSAL
FOREIGN KEY (IDSUCURSAL)
REFERENCES SUCURSAL(IDSUCURSAL)
GO

--ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_SUCURSAL
--FOREIGN KEY (IDSUCURSAL)
--REFERENCES SUCURSAL(IDSucursal);
--HACIA BODEGA
GO
ALTER TABLE ALMACENAMIENTO ADD CONSTRAINT FK_ALMACENAMIENTO_BODEGA
FOREIGN KEY (IDBODEGA)
REFERENCES BODEGA(IDBODEGA)--DOS PRIMMARIAS FALTA

GO
ALTER TABLE PROVEEDORESPORSUCURSAL ADD CONSTRAINT FK_PROVEDORESPORSUCURSAL_ALMACENAMIENTO
FOREIGN KEY (IDBODEGA)
REFERENCES BODEGA(IDBODEGA)--CAMBIE LAS LLAVES PRIMARIAS IDSUCURSAL+CEDULAJURIDICA POR SOLO LA JURIDICA
--HACIA PROVEEDORES
GO
ALTER TABLE PROVEEDORESPORSUCURSAL ADD CONSTRAINT FK_PROVEDORESPORSUCURSAL_PROVEEDOR
FOREIGN KEY (CEDULAJURIDICA)
REFERENCES PROVEEDOR(CEDULAJURIDICA)


GO
ALTER TABLE CORREOPROVEEDOR WITH CHECK ADD CONSTRAINT FK_CORREOPROVEEDOR_PROVEEDOR
FOREIGN KEY (CEDULAJURIDICA)
REFERENCES PROVEEDOR(CEDULAJURIDICA)
GO
ALTER TABLE TELEFONOPROVEEDOR ADD CONSTRAINT FK_TELEFONOPROVEEDOR_PROVEEDOR
FOREIGN KEY (CEDULAJURIDICA)
REFERENCES PROVEEDOR(CEDULAJURIDICA)

GO
ALTER TABLE REPORTEPROVEEDOR ADD CONSTRAINT FK_REPORTEPROVEEDOR_PROVEEDOR
FOREIGN KEY (CEDULAJURIDICA)
REFERENCES PROVEEDOR(CEDULAJURIDICA)
--HACIA VEHICULO
GO
ALTER TABLE REPORTEPROVEEDOR ADD CONSTRAINT FK_TREPORTEPROVEEDOR_VEHICULO
FOREIGN KEY (IDVEHICULO)
REFERENCES VEHICULO(IDVEHICULO)
GO
ALTER TABLE ALMACENAMIENTO ADD CONSTRAINT FK_ALMACENAMIENTO_VEHICULO
FOREIGN KEY (IDVEHICULO)
REFERENCES VEHICULO(IDVEHICULO)
GO
ALTER TABLE FACTURAVEHICULO ADD CONSTRAINT FK_FACTURAVEHICULO_VEHICULO
FOREIGN KEY (IDVEHICULO)
REFERENCES VEHICULO(IDVEHICULO)

GO
ALTER TABLE ContenidoDetalleFactura ADD CONSTRAINT FK_ContenidoDetalleFactura_VEHICULO
FOREIGN KEY (IDVEHICULO)
REFERENCES VEHICULO(IDVEHICULO)

--HACIA DETFACTURA
GO
ALTER TABLE ContenidoDetalleFactura WITH CHECK ADD CONSTRAINT FK_ContenidoDetalleFactura_DETALLEFACTURA
FOREIGN KEY (IDDETALLEFACTURA)
REFERENCES DETALLEFACTURA(IDDETALLEFACTURA)
--HACIA FACTURA 
GO
ALTER TABLE FacturaVEHICULO WITH CHECK ADD CONSTRAINT FK_FacturaVehiculo_FACTURA
FOREIGN KEY (IDFACTURA)
REFERENCES FACTURA(IDFACTURA)
GO
ALTER TABLE FacturacionGenerada WITH CHECK ADD CONSTRAINT FK_FacturacionGenerada_FACTURA
FOREIGN KEY (IDFACTURA)
REFERENCES FACTURA(IDFACTURA)
--Hacia cliente
GO
ALTER TABLE FacturacionGenerada WITH CHECK ADD CONSTRAINT FK_FacturacionGenerada_Cliente
FOREIGN KEY (cedulacliente)
REFERENCES Cliente(cedulacliente)
GO
ALTER TABLE TELEFONOCLIENTE WITH CHECK ADD CONSTRAINT FK_TELEFONOCLIENTE_Cliente
FOREIGN KEY (cedulacliente)
REFERENCES Cliente(cedulacliente)
GO
ALTER TABLE CORREOCLIENTE WITH CHECK ADD CONSTRAINT FK_CORREOCLIENTE_Cliente
FOREIGN KEY (cedulacliente)
REFERENCES Cliente(cedulacliente)
--ALTER TABLE ADMINISTRATIVO  ADD CONSTRAINT PK_ADMIN
--PRIMARY KEY CLUSTERED (IDADMINISTRATIVO)--,IDempleado,IDsucursal)


--IDVendedor int not null
--select * from sys.foreign_key 
--select * from Cliente
--ALTER TABLE PROVEEDORESPORSUCURSAL ADD  IDBodega int not null 
--ALTER TABLE PROVEEDORESPORSUCURSAL  DROP COLUMN IDSUCURSAL ;
--ALTER TABLE DETALLEFACTURA drop CONSTRAINT pkDetalleFactura; 